In [2]:
from utils.const import SAVE_PATH, LOAD_PATH
import numpy as np

In [12]:
np.set_printoptions(suppress=True, precision=4)
np.set_printoptions(linewidth=100, threshold=np.inf)
np.set_printoptions(formatter={'int': '{:5d}'.format})

In [18]:
PATH = SAVE_PATH + ''
DATA_PATH = '../data/hmm_synthetic_dataset(noise-0.5_state-10_obs-500_size-50000).npz'
NUM_STATES = 10

In [9]:
# loaded_npz_trained = np.load(PATH)
loaded_npz_real = np.load(DATA_PATH, allow_pickle=True)

In [38]:
# trans_dist = loaded_npz_trained['trans_dist']
# emis_dist = loaded_npz_trained['emis_dist']
real_trans_dist = loaded_npz_real['real_trans']
real_emis_dist = loaded_npz_real['emis']
observations = loaded_npz_real['observation']
real_hidden_states = loaded_npz_real['real_hidden']

In [39]:
initial_prob = np.array([1 / (NUM_STATES - 1)] * (NUM_STATES - 1))
real_trans_dist = np.vstack((initial_prob.reshape(1, -1), real_trans_dist))
real_trans_dist = np.hstack((np.zeros((NUM_STATES, 1)), real_trans_dist))

In [13]:
print(real_trans_dist)
for seq in observations[:5]:
    print('[' + ', '.join(map(str, seq)) + ']')
for index in range(len(real_hidden_states[:5])):
    print('[' + ', '.join(map(str, real_hidden_states[:5][index])) + ']')
    print("--------------------")

[[0.2532 0.0706 0.0888 0.0549 0.1236 0.0449 0.2569 0.0032 0.1039]
 [0.5177 0.0029 0.128  0.0116 0.0526 0.     0.1001 0.0812 0.1059]
 [0.0141 0.0235 0.0264 0.0019 0.0023 0.0149 0.1922 0.418  0.3069]
 [0.0206 0.1273 0.1187 0.057  0.517  0.     0.0467 0.1071 0.0056]
 [0.0892 0.0101 0.0998 0.4871 0.0902 0.0053 0.0143 0.0438 0.1601]
 [0.2458 0.     0.1682 0.0099 0.0352 0.0025 0.0475 0.4803 0.0106]
 [0.1942 0.0254 0.0136 0.0311 0.1394 0.1462 0.0589 0.244  0.1472]
 [0.4467 0.0001 0.0835 0.0075 0.0185 0.0008 0.259  0.1204 0.0634]
 [0.1549 0.0057 0.0536 0.5995 0.0827 0.     0.0292 0.0107 0.0636]]
[-1, 59, 204, 365, 20, 378, 216, 239, 453, 253, 1, 424, 113, 461, 464, 338, 68, 338, 340, 41, 454, 278, 425, 123, 277, 303]
[-1, 309, 257, 430, 128, 114, 464, 329, 219, 313, 124, 303, 255, 371, 336, 167, 414, 466, 444, 226, 115, 351, 113, 70, 65, 382, 284]
[-1, 309, 427, 430, 242, 382, 364, 242, 247, 169, 246, 158]
[-1, 328, 335, 377, 387, 378, 316, 179, 292, 488, 190, 135, 262, 270, 336, 141, 136]
[-1

In [41]:
test_index = np.random.choice(len(observations), 500)
test_observations = observations[test_index]
test_hidden_states = real_hidden_states[test_index]

In [42]:
for i in range(len(test_observations)):
    assert len(test_observations[i]) == len(test_hidden_states[i])

In [44]:
for seq in test_observations[:5]:
    print('[' + ', '.join(map(str, seq)) + ']')
for index in range(len(test_hidden_states[:5])):
    print('[' + ', '.join(map(str, test_hidden_states[:5][index])) + ']')
    print("--------------------")

[-1, 359, 200, 410, 25, 193, 388, 115, 342, 8, 476, 190, 258, 276, 63, 453, 309, 475, 397, 401, 136, 27, 243, 362, 108, 5, 329, 373, 469]
[-1, 213, 155, 424, 397, 345, 416, 74, 265, 71, 430, 404, 281, 207, 35]
[-1, 341, 472, 429, 428, 81, 474, 158, 194, 44, 70, 243, 287, 323, 431, 162, 77, 263, 117, 367, 33, 9, 198, 464, 0]
[-1, 135, 223, 262, 379, 65, 23, 150, 77, 133, 397, 91, 457]
[-1, 44, 276, 332, 364, 41, 226, 190, 63, 213, 66, 173, 12, 138, 155, 327, 22, 64, 242, 191, 50, 439, 424, 473, 95, 292, 61, 426, 52, 407]
[0, 6, 8, 1, 7, 6, 8, 1, 6, 3, 9, 4, 5, 4, 5, 4, 3, 7, 8, 7, 3, 8, 1, 7, 7, 9, 4, 5, 9]
--------------------
[0, 7, 6, 7, 1, 1, 5, 4, 4, 8, 7, 6, 8, 9, 1]
--------------------
[0, 3, 8, 1, 7, 7, 9, 4, 5, 9, 3, 8, 8, 1, 9, 7, 1, 3, 9, 4, 3, 9, 9, 4, 5]
--------------------
[0, 8, 8, 4, 2, 3, 8, 7, 5, 4, 5, 9, 4]
--------------------
[0, 2, 7, 9, 5, 4, 3, 7, 5, 9, 3, 3, 8, 8, 7, 8, 8, 1, 7, 6, 1, 5, 1, 7, 6, 8, 1, 6, 8, 9]
--------------------


Random select 500 sequences from the training dataset, 
run viterbi to decode based on trained distributions. 
calculate 0-1 loss. 

In [51]:
def viterbi(observations, num_states, transition_prob, emission_prob):
    
    V = np.zeros((num_states, len(observations)))
    path = {}
    # first column of V is the transition prob from state 0 
    V[:, 0] = transition_prob[0, :]

    for t in range(1, len(observations)):
        for s in range(1, num_states):
            prob = V[:, t-1] * transition_prob[:, s] * emission_prob[s - 1, observations[t]]
            V[s, t] = np.max(prob)
            path[s, t] = np.argmax(prob)

    optimal_path = []
    last_state = np.argmax(V[:, -1])
    optimal_path.append(last_state)

    for t in range(len(observations) - 1, 1, -1):
        last_state = path[last_state, t]
        optimal_path.insert(0, last_state)
        
    optimal_path.insert(0, 0)

    return optimal_path

In [54]:
for i, obs in enumerate(test_observations[10:15]):
    decoded_hidden_states = viterbi(obs, NUM_STATES, real_trans_dist, real_emis_dist)
    print(len(decoded_hidden_states), len(test_hidden_states[i + 10]))
    print("Most probable states:", decoded_hidden_states)
    print("Real hidden states: ", test_hidden_states[i + 10])

13 13
Most probable states: [0, 7, 8, 7, 8, 1, 9, 4, 5, 4, 5, 3, 8]
Real hidden states:  [0, 5, 5, 4, 5, 3, 9, 4, 5, 3, 9, 3, 8]
11 11
Most probable states: [0, 1, 1, 5, 4, 3, 8, 8, 7, 8, 1]
Real hidden states:  [0, 1, 1, 5, 4, 8, 1, 5, 7, 8, 9]
25 25
Most probable states: [0, 1, 1, 7, 6, 1, 7, 1, 1, 1, 7, 8, 1, 4, 5, 3, 8, 8, 1, 1, 1, 2, 1, 7, 8]
Real hidden states:  [0, 9, 1, 7, 3, 7, 6, 3, 7, 9, 4, 5, 4, 2, 7, 1, 2, 8, 1, 1, 1, 7, 9, 5, 1]
30 30
Most probable states: [0, 4, 5, 4, 5, 9, 4, 5, 4, 2, 1, 1, 3, 8, 7, 8, 1, 2, 1, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5]
Real hidden states:  [0, 4, 5, 4, 2, 7, 4, 5, 5, 1, 2, 1, 3, 8, 1, 1, 5, 4, 5, 3, 8, 7, 4, 5, 4, 5, 4, 3, 1, 7]
18 18
Most probable states: [0, 4, 5, 4, 5, 9, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 1, 7]
Real hidden states:  [0, 5, 1, 2, 7, 9, 4, 5, 4, 7, 8, 1, 5, 4, 2, 3, 8, 7]


Even created by real transition and emission distributions, the viterbi decoded sequence is not same as the orginal hidden states. So want to use real and sampled distributions to decode at the same time and compare the results. 